[package]
name = "rust-playground"
version = "0.1.0"
edition = "2024"

[build-dependencies]
gl_generator = "0.14"

[dependencies]
anyhow = "1.0.98"
glutin = "0.32.2"
glutin-winit = "0.5.0"
winit = "0.30.9"
